# SPDX-FileCopyrightText: Contributors to the Switchgear Thermal Model project <core@alliander.com>
# SPDX-License-Identifier: MPL-2.0

# Trigger reusable workflow.

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please refer to the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # `pip` also enables Poetry
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    cooldown:
      default-days: 3