# SPDX-FileCopyrightText: Contributors to the Switchgear Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0


[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "2700fd5671c633760d912769c041bfcde2b9a01b" # v0.15.22
hooks = [
  {
    id = "ruff",
    args = ["--fix"]
  },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "41e691678310dfd3833f7ab4e180ddb014310356" # v2.3.0
hooks = [
  {
    id = "mypy",
    additional_dependencies = [
      "pytest",
      "pytest-cov"
    ]
  }
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "57b21406f092110c18776e39b0bda50d37c945c8" # v2.4.3
hooks = [
  {
    id = "codespell",
    exclude = "pyproject.toml|poetry.lock|docs/theoretical_documentation/model.md|docs/examples/"
  }
]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0" # v0.49.1
hooks = [
  {
    id = "markdownlint",
    args = [
      "--ignore",
      "docs/theoretical_documentation/model.md"
    ]
  }
]
