# SPDX-FileCopyrightText: Contributors to the Switchgear Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

sonar.projectKey=alliander-opensource_switchgear-thermal-model
sonar.organization=alliander-opensource
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=\
    **/tests/**, \
    **/docs/**, \
  