# SPDX-FileCopyrightText: Contributors to the Switchgear Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

# This workflow is used to run the example notebooks and check if they execute without raising any exceptions.

name: uv.yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate_uv:
    runs-on:
      group: managed-linux
    permissions:
      contents: read # for actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version:  ${{ inputs.python-version }}

      - name: Install uv
        run: pipx install --python python${{ inputs.python-version }} uv==0.11.31

      - name: Install prek
        run: uv lock

      - name: print uv.lock
        shell: bash
        run: cat uv.lock